#!/usr/bin/env bash
set -eEuo pipefail

echo_exit() {
    local message=$1
    local code=$2

    echo "$message"
    echo "Exiting..."
    exit "$code"
}

[[ $OSTYPE != darwin* ]] && echo_exit "This executable only supports macOS, not $OSTYPE." 1

# Load some functions
source "$ROCK_DIR"/lib/get-option.sh

# Get installation directory
ROCK_DIR=$(dirname "$(readlink "$0")")

# Load specific command
SUBCOMMAND=$1
cd "$ROCK_DIR"/bin
for command in *; do
    if [[ "$command" == "$SUBCOMMAND".sh ]]; then
        source "$command"
    fi
done
echo_exit "Command '$SUBCOMMAND' not found." 127
