#!/usr/bin/env bash
set -eEuo pipefail

echo_exit() {
    local message=$1
    local code=$2

    echo "$message"
    echo "Exiting..."
    exit "$code"
}

[[ $OSTYPE != darwin* ]] && echo_exit "This executable only supports macOS, not $OSTYPE." 1
[[ $(uname -m) != "arm64" ]] && echo_exit "This executable only supports apple silicon macs." 1

# Get installation directory
ROCK_DIR=$(dirname "$(realpath "$0")")

# Load some functions
source "$ROCK_DIR"/lib/get-option.sh

# Load specific command
SUBCOMMAND=$1
cd "$ROCK_DIR"/bin
for command in *; do
    if [[ "$command" == "$SUBCOMMAND".sh ]]; then
        # shellcheck disable=SC1090
        source "$command"
        exit 0
    fi
done
echo_exit "Command '$SUBCOMMAND' not found." 127
