" Disable compatibility with vi which can cause unexpected issues.
set nocompatible

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

" Enable plugins and load plugin for the detected file type.
filetype plugin on

" Load an indent file for the detected file type.
filetype indent on

" Turn syntax highlighting on.
syntax on

" Add numbers to each line on the left-hand side.
set number

" Set shift width to 4 spaces.
set shiftwidth=4

" Set tab width to 4 columns.
set tabstop=4

" Use space characters instead of tabs.
set expandtab

" Number of spaces in tab when editing
set softtabstop=4

" Do not save backup files.
set nobackup

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=10

" Do not wrap lines. Allow long lines to extend as far as the line goes.
set nowrap

" Make wrap lines when using arrow keys at the beginning/end
set whichwrap+=<,>,h,l,[,]

" While searching though a file incrementally highlight matching characters as you type.
set incsearch

" Ignore capital letters during search.
set ignorecase

" Override the ignorecase option if searching for capital letters.
" This will allow you to search specifically for capital letters.
set smartcase

" Show partial command you type in the last line of the screen.
set showcmd

" Show the mode you are on the last line.
set showmode

" Show matching words during a search.
set showmatch

" Use highlighting when doing a search.
set hlsearch

" Set the commands to save in history default number is 20.
set history=1000

" Enable auto completion menu after pressing TAB.
set wildmenu

" Make wildmenu behave like similar to Bash completion.
set wildmode=list:longest

" There are certain files that we would never want to edit with Vim.
" Wildmenu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Make yank copy to system clipboard
set clipboard=unnamed,unnamedplus

"
set backspace=indent,eol,start


" PLUGINS ---------------------------------------------------------------- {{{

" Set plugin path
set runtimepath+=$VIM_DIR/autoload

call plug#begin($VIM_DIR . '/plugged')

  Plug 'dense-analysis/ale'
  Plug 'preservim/nerdtree'
  Plug 'tomasiser/vim-code-dark'
  Plug 'jiangmiao/auto-pairs'

  " Source personal plugins if the file exists
  if filereadable($VIM_DIR . '/personal-plugins.vim')
    for line in readfile($VIM_DIR . '/personal-plugins.vim')
      " Skip empty lines and comments
      if line =~ '^\s*$' || line =~ '^\s*"'
        continue
      endif
      " Trim whitespace and wrap in Plug command
      let plugin = substitute(line, '^\s*\|\s*$', '', 'g')
      execute 'Plug ' . string(plugin)
    endfor
  endif

call plug#end()

" }}}

" MAPPINGS --------------------------------------------------------------- {{{

" Set space as the leader key.
let mapleader = " "

" Press the space bar to type the : character in command mode.
nnoremap <space> :

" Pressing the letter o will open a new line below the current one.
" Exit insert mode after creating a new line above or below the current line.
nnoremap o o<esc>
nnoremap O O<esc>

" Center the cursor vertically when moving to the next word during a search.
nnoremap n nzz
nnoremap N Nzz

" Enable easy toggling of line numbers for copying with mouse
nnoremap L :set invnumber <CR>

" }}}

" VIMSCRIPT -------------------------------------------------------------- {{{

" This will enable code folding.
" Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" If the current file type is HTML, set indentation to 2 spaces.
autocmd Filetype html setlocal tabstop=2 shiftwidth=2 expandtab

" If Vim version is equal to or greater than 7.3 enable undofile.
" This allows you to undo changes to a file even after saving it.
let ud = $VIM_DIR . '/backup'
set undodir=&ud
set undofile
set undoreload=1000

colorscheme codedark
set cursorline
set cursorlineopt=number
autocmd ColorScheme * highlight CursorLineNr cterm=bold term=bold gui=bold

" :W sudo saves the file
" (useful for handling the permission-denied error)
command! -bar  W execute 'w !sudo tee % > /dev/null' <bar> edit!
command! Wq W|q

" Enter Normal Mode more easily
imap jk <esc>
imap kj <esc>

" Enter will unhighlight search results
nnoremap <CR> :noh<CR>

" Move to beginning/end of line more easily
noremap B ^
noremap E $

" Trim trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Trim blank lines at end of file on save
function TrimEndLines()
    let save_cursor = getpos(".")
    silent! %s#\($\n\s*\)\+\%$##
    call setpos('.', save_cursor)
endfunction
autocmd BufWritePre * call TrimEndLines()

" }}}

" STATUS LINE ------------------------------------------------------------ {{{

" Clear status line when vimrc is reloaded.
set statusline=

" Status line left side.
set statusline+=\ %F\ %M\ %Y\ %R

" Use a divider to separate the left side from the right side.
set statusline+=%=

" Status line right side.
set statusline+=\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ percent:\ %p%%

" Show the status on the second to last line.
set laststatus=2

" }}}
